import React, { useEffect, useMemo, useState } from 'react';
import { useApp } from '../context/AppContext';
import { CertificateFrontPage, CertificateBackPage } from '../components/CertificateDocument';
import { CertificateModal } from '../components/CertificateModal';
import { Certificate } from '../types';
import confetti from 'canvas-confetti';
import { ArrowLeft, ArrowRight, CheckCircle, Eye, FileText, Layers, Loader2, User, AlertTriangle } from 'lucide-react';

const onlyDigits = (value: string, maxLength = 11) => value.replace(/\D/g, '').slice(0, maxLength);
const formatCpfInput = (value: string) => { const d = onlyDigits(value); return d.replace(/^(\d{3})(\d)/, '$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/, '$1.$2.$3').replace(/(\d{3})(\d{1,2})$/, '$1-$2'); };
const CNH_CATEGORIES = ['A','B','C','D','E','AB','AC','AD','AE'];
const DRAFT_KEY = 'certifyai_cvte_draft_v1';

export const CreateCertificateView: React.FC = () => {
  const { courses, students, certificates, institution, issueCertificate, setCurrentView, setValidationSearchCode } = useApp();
  const course = courses[0];
  const prefillStudentId = typeof window !== 'undefined' ? sessionStorage.getItem('certifyai_prefill_student') || '' : '';
  const initialStudent = students.find((student) => student.id === prefillStudentId);
  const savedDraft = useMemo(() => { try { return typeof window !== 'undefined' ? JSON.parse(localStorage.getItem(DRAFT_KEY) || '{}') : {}; } catch { return {}; } }, []);
  const [currentStep, setCurrentStep] = useState<1 | 2>(1);
  const [previewTab, setPreviewTab] = useState<'front' | 'back' | 'both'>('front');
  const [selectedStudentId, setSelectedStudentId] = useState(initialStudent?.id || '');
  const [studentName, setStudentName] = useState(initialStudent?.fullName || savedDraft.studentName || '');
  const [studentEmail, setStudentEmail] = useState(initialStudent?.email || savedDraft.studentEmail || '');
  const [studentDocument, setStudentDocument] = useState(onlyDigits(initialStudent?.documentNumber || savedDraft.studentDocument || ''));
  const [registrationNumber, setRegistrationNumber] = useState(onlyDigits(initialStudent?.registrationNumber || savedDraft.registrationNumber || ''));
  const [cnhCategory, setCnhCategory] = useState(initialStudent?.cnhCategory || savedDraft.cnhCategory || 'AD');
  const [startDate, setStartDate] = useState(savedDraft.startDate || course?.startDate || '');
  const [endDate, setEndDate] = useState(savedDraft.endDate || course?.endDate || '');
  const [issueDate, setIssueDate] = useState(savedDraft.issueDate || new Date().toISOString().split('T')[0]);
  const [location, setLocation] = useState(savedDraft.location || `${institution.city || 'Brasília'}-${institution.state || 'DF'}`);
  const [createdCertificate, setCreatedCertificate] = useState<Certificate | null>(null);
  const [isIssuing, setIsIssuing] = useState(false);
  const [duplicateWarning, setDuplicateWarning] = useState<Certificate | null>(null);

  useEffect(() => { sessionStorage.removeItem('certifyai_prefill_student'); sessionStorage.removeItem('certifyai_prefill_course'); }, []);
  useEffect(() => { if (!selectedStudentId) return; const s=students.find(x=>x.id===selectedStudentId); if(!s)return; setStudentName(s.fullName);setStudentEmail(s.email||'');setStudentDocument(onlyDigits(s.documentNumber||''));setRegistrationNumber(onlyDigits(s.registrationNumber||''));setCnhCategory(s.cnhCategory||'AD'); }, [selectedStudentId, students]);
  useEffect(() => { localStorage.setItem(DRAFT_KEY, JSON.stringify({studentName,studentEmail,studentDocument,registrationNumber,cnhCategory,startDate,endDate,issueDate,location})); }, [studentName,studentEmail,studentDocument,registrationNumber,cnhCategory,startDate,endDate,issueDate,location]);

  const validate = () => {
    if (!studentName.trim()) return alert('Informe o nome completo do condutor.'), false;
    if (studentDocument.length !== 11) return alert('O CPF deve conter exatamente 11 dígitos.'), false;
    if (registrationNumber.length !== 11) return alert('O Nº REGISTRO deve conter exatamente 11 dígitos.'), false;
    if (!cnhCategory) return alert('Selecione a categoria da CNH.'), false;
    if (studentEmail.trim() && !/^\S+@\S+\.\S+$/.test(studentEmail.trim())) return alert('Informe um e-mail válido.'), false;
    if (!course) return alert('O curso CVTE não está configurado.'), false;
    if (!startDate || !endDate || startDate > endDate) return alert('Revise o período do curso.'), false;
    if (!issueDate || !location.trim()) return alert('Informe data e local de emissão.'), false;
    return true;
  };
  const findDuplicate = () => certificates.find(c => c.status==='active' && onlyDigits(c.studentDocument||'')===studentDocument && c.courseId===course?.id) || null;
  const performIssue = () => {
    if (isIssuing || !course) return; setIsIssuing(true);
    try { const cert=issueCertificate({studentId:selectedStudentId||`student-${Date.now()}`,studentName:studentName.trim().toUpperCase(),studentEmail:studentEmail.trim()||undefined,studentDocument,registrationNumber,cnhCategory,courseId:course.id,courseName:course.name,courseSubhead:course.courseSubhead||'Condutores de Veículos de Transporte de Emergência',workloadHours:course.workloadHours,modality:course.modality,instructorName:course.instructorName||'Instrutor Responsável',institutionName:institution.name,institutionCnpj:institution.institutionCnpj,legalInstruction:institution.legalInstruction,contranResolution:institution.contranResolution,validityText:institution.validityText,syllabus:course.syllabus,issueDate,startDate,endDate,location,signatoryName:institution.signatoryName||'Diretor Geral',signatoryRole:institution.signatoryRole||'Diretor Geral',signatoryCpf:institution.signatoryCpf,templateId:'official'}); setCreatedCertificate(cert);setDuplicateWarning(null);localStorage.removeItem(DRAFT_KEY);try{confetti({particleCount:70,spread:70,origin:{y:.6}})}catch{} } catch { alert('Erro ao emitir o certificado.'); } finally { setIsIssuing(false); }
  };
  const issue=()=>{if(!validate())return;const d=findDuplicate();if(d){setDuplicateWarning(d);return;}performIssue();};
  const resetForNext=()=>{setCreatedCertificate(null);setCurrentStep(1);setSelectedStudentId('');setStudentName('');setStudentEmail('');setStudentDocument('');setRegistrationNumber('');setCnhCategory('AD');localStorage.removeItem(DRAFT_KEY);};
  const previewCertificate={studentName:studentName.toUpperCase()||'NOME DO CONDUTOR',studentDocument:studentDocument||'00000000000',registrationNumber:registrationNumber||'00000000000',cnhCategory,courseName:course?.name||'Curso Especializado para Condutores de Veículos de Transporte de Emergência',courseSubhead:course?.courseSubhead||'Condutores de Veículos de Transporte de Emergência',workloadHours:course?.workloadHours||50,modality:course?.modality||'presencial',instructorName:course?.instructorName||'',institutionName:institution.name,institutionCnpj:institution.institutionCnpj,legalInstruction:institution.legalInstruction,contranResolution:institution.contranResolution,validityText:institution.validityText,syllabus:course?.syllabus,issueDate,startDate,endDate,location,signatoryName:institution.signatoryName||'Diretor Geral',signatoryRole:institution.signatoryRole||'Diretor Geral',signatoryCpf:institution.signatoryCpf,code:'001/CVTE/'+new Date().getFullYear()};

  return <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-6xl mx-auto w-full">
    <div><div className="inline-flex px-2.5 py-1 rounded-full bg-amber-100 text-amber-800 text-xs font-bold">Modelo Oficial • CVTE</div><h1 className="text-2xl sm:text-3xl font-extrabold mt-2">Emitir Certificado</h1><p className="text-sm text-slate-500">Preencha apenas os dados variáveis do condutor. O restante vem da configuração oficial.</p></div>
    {currentStep===1 ? <form onSubmit={e=>{e.preventDefault();if(validate())setCurrentStep(2)}} className="space-y-5">
      <section className="bg-white dark:bg-slate-900 p-6 rounded-2xl border space-y-4"><div className="flex items-center gap-2 border-b pb-3"><User className="w-5 h-5 text-indigo-600"/><div><h2 className="font-bold">Dados do Condutor</h2><p className="text-xs text-slate-500">Nome será impresso em letras maiúsculas.</p></div></div>
        {students.length>0&&<select value={selectedStudentId} onChange={e=>setSelectedStudentId(e.target.value)} className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"><option value="">Novo condutor / preencher manualmente</option>{students.map(s=><option key={s.id} value={s.id}>{s.fullName}</option>)}</select>}
        <div className="grid sm:grid-cols-2 gap-3"><input value={studentName} onChange={e=>setStudentName(e.target.value)} placeholder="Nome completo *" className="px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border uppercase"/><input value={studentEmail} onChange={e=>setStudentEmail(e.target.value)} placeholder="E-mail (opcional)" type="email" className="px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/><div><input value={formatCpfInput(studentDocument)} onChange={e=>setStudentDocument(onlyDigits(e.target.value))} inputMode="numeric" placeholder="CPF *" className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/><p className="mt-1 text-[10px] text-slate-500">{studentDocument.length}/11 dígitos</p></div><div><input value={registrationNumber} onChange={e=>setRegistrationNumber(onlyDigits(e.target.value))} inputMode="numeric" maxLength={11} placeholder="Nº REGISTRO / CONDUTOR *" className="w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/><p className="mt-1 text-[10px] text-slate-500">{registrationNumber.length}/11 dígitos</p></div><label className="text-xs font-semibold">Categoria CNH<select value={cnhCategory} onChange={e=>setCnhCategory(e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border">{CNH_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label></div>
      </section>
      <section className="bg-white dark:bg-slate-900 p-6 rounded-2xl border"><h2 className="font-bold mb-3">Período e emissão</h2><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-semibold">Início<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label><label className="text-xs font-semibold">Término<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label><label className="text-xs font-semibold">Data de emissão<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label><label className="text-xs font-semibold">Local<input value={location} onChange={e=>setLocation(e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label></div><p className="mt-3 text-xs text-slate-500">Curso: <strong>{course?.name}</strong> • Carga horária: <strong>{course?.workloadHours||50}h/a</strong></p></section>
      <div className="flex justify-end"><button type="submit" className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white font-bold rounded-xl"><Eye className="w-4 h-4"/>Revisar certificado<ArrowRight className="w-4 h-4"/></button></div>
    </form> : <div className="space-y-5"><div className="bg-white dark:bg-slate-900 border rounded-2xl p-4"><h2 className="font-bold">Confirme antes de emitir</h2><div className="mt-3 grid sm:grid-cols-3 gap-2 text-xs"><div><span className="text-slate-500">Condutor</span><strong className="block">{studentName.toUpperCase()}</strong></div><div><span className="text-slate-500">CPF</span><strong className="block">{formatCpfInput(studentDocument)}</strong></div><div><span className="text-slate-500">Registro / CNH</span><strong className="block">{registrationNumber} • {cnhCategory}</strong></div></div></div><div className="sticky top-3 z-30 bg-white dark:bg-slate-900 border rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3"><button onClick={()=>setCurrentStep(1)} className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-sm font-semibold"><ArrowLeft className="w-4 h-4"/>Voltar e corrigir</button><div className="flex rounded-lg bg-slate-100 dark:bg-slate-800 p-1 text-xs"><button onClick={()=>setPreviewTab('front')} className="px-3 py-1.5">Frente</button><button onClick={()=>setPreviewTab('back')} className="px-3 py-1.5">Verso</button><button onClick={()=>setPreviewTab('both')} className="px-3 py-1.5">Ambos</button></div><button onClick={issue} disabled={isIssuing} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-600 disabled:opacity-50 text-white text-sm font-bold">{isIssuing?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle className="w-4 h-4"/>}Emitir certificado</button></div><div className="bg-slate-200 dark:bg-slate-950 rounded-2xl p-5 overflow-x-auto flex flex-col items-center gap-6">{(previewTab==='front'||previewTab==='both')&&<div><div className="text-xs font-bold text-slate-500 mb-2 flex gap-1"><FileText className="w-4 h-4"/>Frente</div><CertificateFrontPage certificate={previewCertificate}/></div>}{(previewTab==='back'||previewTab==='both')&&<div><div className="text-xs font-bold text-slate-500 mb-2 flex gap-1"><Layers className="w-4 h-4"/>Verso</div><CertificateBackPage certificate={previewCertificate}/></div>}</div></div>}
    {duplicateWarning&&<div className="fixed inset-0 z-[70] bg-slate-900/70 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl bg-white dark:bg-slate-900 p-6"><div className="flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600"/><div><h3 className="font-extrabold">Condutor já certificado</h3><p className="text-sm text-slate-500">Este CPF já possui o certificado ativo <strong>{duplicateWarning.code}</strong>.</p></div></div><div className="mt-6 flex flex-wrap justify-end gap-2"><button onClick={()=>{setValidationSearchCode(duplicateWarning.code);setCurrentView('validate');setDuplicateWarning(null)}} className="px-4 py-2 rounded-xl bg-indigo-50 text-indigo-700 font-bold">Visualizar existente</button><button onClick={()=>setDuplicateWarning(null)} className="px-4 py-2 rounded-xl bg-slate-100">Voltar</button><button onClick={performIssue} disabled={isIssuing} className="px-4 py-2 rounded-xl bg-amber-600 text-white font-bold">Emitir mesmo assim</button></div></div></div>}
    {createdCertificate&&<CertificateModal certificate={createdCertificate} isOpen={true} onClose={resetForNext} setCurrentView={setCurrentView} setValidationSearchCode={setValidationSearchCode}/>} 
  </div>;
};
