import React,{useEffect,useState}from'react';import{useApp}from'../context/AppContext';import{Certificate}from'../types';import{CertificateModal}from'../components/CertificateModal';import{ShieldCheck,Search,CheckCircle2,XCircle,AlertTriangle,User,Award,Calendar,Eye,Ban}from'lucide-react';
const cpf=(v='')=>{const d=v.replace(/\D/g,'').slice(0,11);return d.length===11?`${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`:d||'-'};const date=(v?:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'-';
export const ValidateCertificateView:React.FC=()=>{const{certificates,validationSearchCode,setValidationSearchCode}=useApp();const[inputCode,setInputCode]=useState(validationSearchCode||'');const[searched,setSearched]=useState(false);const[found,setFound]=useState<Certificate|null>(null);const[modal,setModal]=useState<Certificate|null>(null);
const execute=(value:string)=>{const clean=value.trim().toUpperCase();if(!clean)return;setSearched(true);setValidationSearchCode(clean);setFound(certificates.find(c=>c.code.toUpperCase()===clean)||null)};useEffect(()=>{if(validationSearchCode){setInputCode(validationSearchCode);execute(validationSearchCode)}},[]);
return <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-4xl mx-auto w-full"><div className="text-center pt-4"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-50 text-indigo-700 text-xs font-bold"><ShieldCheck className="w-4 h-4"/>Consulta CVTE</div><h1 className="mt-3 text-3xl font-black">Validar Certificado</h1><p className="mt-2 text-sm text-slate-500">Digite o código exatamente como aparece no certificado, por exemplo <strong>001/CVTE/2026</strong>.</p></div><form onSubmit={e=>{e.preventDefault();execute(inputCode)}} className="bg-white dark:bg-slate-900 p-5 sm:p-6 rounded-2xl border flex flex-col sm:flex-row gap-2"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 w-5 h-5 text-slate-400"/><input autoFocus value={inputCode} onChange={e=>setInputCode(e.target.value.toUpperCase())} placeholder="001/CVTE/2026" className="w-full pl-12 pr-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800 border font-mono font-bold uppercase"/></div><button className="px-7 py-3.5 rounded-xl bg-indigo-600 text-white font-bold flex items-center justify-center gap-2"><ShieldCheck className="w-5 h-5"/>Validar</button></form>
{searched&&!found&&<StatusCard tone="neutral" icon={<XCircle className="w-8 h-8"/>} title="Certificado não encontrado"><p>Confira o código informado e tente novamente.</p></StatusCard>}
{found&&found.status==='cancelled'&&<StatusCard tone="danger" icon={<Ban className="w-8 h-8"/>} title="Certificado cancelado"><Details cert={found}/><div className="mt-4 rounded-xl bg-rose-50 border border-rose-200 p-4 text-sm text-rose-800"><strong className="flex items-center gap-1"><AlertTriangle className="w-4 h-4"/>Motivo do cancelamento</strong><p className="mt-1">{found.cancellationReason||'Certificado cancelado pela instituição emissora.'}</p>{found.cancelledAt&&<p className="mt-1 text-xs">Cancelado em {new Date(found.cancelledAt).toLocaleDateString('pt-BR')}</p>}</div></StatusCard>}
{found&&found.status!=='cancelled'&&<StatusCard tone="success" icon={<CheckCircle2 className="w-8 h-8"/>} title="Certificado válido"><Details cert={found}/><button onClick={()=>setModal(found)} className="mt-5 w-full sm:w-auto px-5 py-2.5 rounded-xl bg-indigo-600 text-white font-bold text-sm flex items-center justify-center gap-2"><Eye className="w-4 h-4"/>Visualizar certificado</button></StatusCard>}
<div className="rounded-xl bg-slate-100 dark:bg-slate-900 p-4 text-xs text-slate-500">A consulta verifica os certificados armazenados neste navegador. Não é necessário QR Code, login ou conexão com banco de dados.</div>{modal&&<CertificateModal certificate={modal} isOpen onClose={()=>setModal(null)}/>}</div>};
const Details:React.FC<{cert:Certificate}>=({cert})=><div className="mt-5 grid sm:grid-cols-2 gap-3"><Box icon={<User className="w-4 h-4"/>} label="Condutor" value={cert.studentName} sub={`CPF ${cpf(cert.studentDocument)}`}/><Box icon={<Award className="w-4 h-4"/>} label="Curso" value={cert.courseName} sub={`${cert.workloadHours} horas`}/><Box icon={<ShieldCheck className="w-4 h-4"/>} label="Código" value={cert.code} sub={`Registro ${cert.registrationNumber||'-'} • CNH ${cert.cnhCategory||'-'}`}/><Box icon={<Calendar className="w-4 h-4"/>} label="Emissão" value={date(cert.issueDate)} sub={cert.institutionName}/></div>;
const Box:React.FC<{icon:React.ReactNode;label:string;value:string;sub?:string}>=({icon,label,value,sub})=><div className="rounded-xl bg-slate-50 dark:bg-slate-800 border p-4"><div className="flex items-center gap-1.5 text-xs text-slate-500">{icon}{label}</div><div className="mt-1 font-bold">{value}</div>{sub&&<div className="mt-1 text-xs text-slate-500">{sub}</div>}</div>;
const StatusCard:React.FC<{tone:'success'|'danger'|'neutral';icon:React.ReactNode;title:string;children:React.ReactNode}>=({tone,icon,title,children})=>{const cls=tone==='success'?'border-emerald-400 text-emerald-700':tone==='danger'?'border-rose-400 text-rose-700':'border-slate-300 text-slate-600';return <div className={`bg-white dark:bg-slate-900 rounded-2xl border-2 ${cls} p-6`}><div className="flex items-center gap-3">{icon}<h2 className="text-2xl font-black">{title}</h2></div><div className="mt-3 text-sm text-slate-600 dark:text-slate-300">{children}</div></div>};
