import React,{useEffect,useState}from'react';
import{consumeAuthRedirect,getSupabaseSession,recoverPassword,saveSupabaseSession,signInWithPassword,signUp,SupabaseSession,updatePassword}from'../lib/supabase';
import{clearCloudOperationalData,loadCloudData,uploadLocalData}from'../services/database';
import{Cloud,Loader2,LockKeyhole}from'lucide-react';
import{INITIAL_COURSES,INITIAL_INSTITUTION,mergeRequiredCourses}from'../utils/storage';

const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const friendly=(error:unknown)=>{const text=error instanceof Error?error.message:String(error);try{const parsed=JSON.parse(text);return parsed.msg||parsed.message||parsed.error_description||'Não foi possível acessar a conta.'}catch{return text.includes('Invalid login credentials')?'E-mail ou senha incorretos.':text}};
const LOGIN_GUARD_KEY='certifyai_login_guard_v1';const MAX_LOGIN_ATTEMPTS=5;const LOCK_DURATION_MS=15*60*1000;
type LoginGuard={attempts:number;lockedUntil:number};
const loadLoginGuard=():LoginGuard=>{try{const value=JSON.parse(localStorage.getItem(LOGIN_GUARD_KEY)||'null') as LoginGuard|null;if(!value||value.lockedUntil<=Date.now())return{attempts:0,lockedUntil:0};return value;}catch{return{attempts:0,lockedUntil:0}}};
const isInvalidCredentials=(error:unknown)=>{try{const parsed=JSON.parse(error instanceof Error?error.message:String(error));return parsed.code==='invalid_credentials'||String(parsed.message||parsed.msg||'').toLowerCase().includes('invalid login credentials');}catch{return String(error).toLowerCase().includes('invalid login credentials')}};
const isPublicValidation=()=>location.pathname.startsWith('/verificar/')||new URLSearchParams(location.search).has('verify')||new URLSearchParams(location.search).has('code');

export const AuthGate:React.FC<{children:React.ReactNode}>=({children})=>{
 const[session,setSession]=useState<SupabaseSession|null>(getSupabaseSession);
 const[ready,setReady]=useState(false);const[loading,setLoading]=useState(false);
 const[register,setRegister]=useState(false);const[recoveryRequest,setRecoveryRequest]=useState(false);const[recoveryMode,setRecoveryMode]=useState(()=>new URLSearchParams(location.hash.replace(/^#/,'')).get('type')==='recovery'||new URLSearchParams(location.search).get('recovery')==='1');const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[loginGuard,setLoginGuard]=useState<LoginGuard>(loadLoginGuard);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const prepare=async(active:SupabaseSession)=>{
  const resetKey='certifyai_operational_reset_2026_09_15';
  if(localStorage.getItem(resetKey)!=='done'){
   await clearCloudOperationalData();
   localStorage.setItem('certifyai_students','[]');localStorage.setItem('certifyai_classes','[]');localStorage.setItem('certifyai_certificates','[]');localStorage.setItem('certifyai_audit_logs','[]');localStorage.setItem(resetKey,'done');
  }
  const cloud=await loadCloudData();
  const local={institution:read('certifyai_institution',INITIAL_INSTITUTION),courses:read('certifyai_courses',INITIAL_COURSES),students:read('certifyai_students',[]),classes:read('certifyai_classes',[]),certificates:read('certifyai_certificates',[]),auditLogs:read('certifyai_audit_logs',[])};
  const hasCloud=Boolean(cloud.institution||cloud.courses.length||cloud.students.length||cloud.classes.length||cloud.certificates.length||cloud.auditLogs.length);
  const merged=hasCloud?{institution:cloud.institution||local.institution,courses:mergeRequiredCourses(cloud.courses),students:cloud.students,classes:cloud.classes,certificates:cloud.certificates,auditLogs:cloud.auditLogs}:{...local,courses:mergeRequiredCourses(local.courses.length?local.courses:INITIAL_COURSES)};
  localStorage.setItem('certifyai_institution',JSON.stringify(merged.institution));localStorage.setItem('certifyai_courses',JSON.stringify(merged.courses));localStorage.setItem('certifyai_students',JSON.stringify(merged.students));localStorage.setItem('certifyai_classes',JSON.stringify(merged.classes));localStorage.setItem('certifyai_certificates',JSON.stringify(merged.certificates));localStorage.setItem('certifyai_audit_logs',JSON.stringify(merged.auditLogs));
  await uploadLocalData(active.user.id,merged);
  setSession(active);
 };
 useEffect(()=>{if(isPublicValidation()){setReady(true);return;}void(async()=>{try{const redirected=await consumeAuthRedirect();const active=redirected||getSupabaseSession();if(active)await prepare(active);}catch(e){saveSupabaseSession(null);setSession(null);setError(friendly(e));}finally{setReady(true);}})();},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');
  if(recoveryRequest){if(!email.trim()){setError('Informe seu e-mail.');return;}setLoading(true);try{await recoverPassword(email.trim());setMessage('Se o e-mail estiver cadastrado, enviaremos um link para redefinir a senha.');}catch(e){setError(friendly(e));}finally{setLoading(false);}return;}
  if(loginGuard.lockedUntil>Date.now()){setError(`Muitas tentativas incorretas. Tente novamente em ${Math.max(1,Math.ceil((loginGuard.lockedUntil-Date.now())/60000))} minuto(s).`);return;}
  if(password.length<6){setError('A senha deve ter pelo menos 6 caracteres.');return;}setLoading(true);try{if(register){if(!name.trim()){setError('Informe seu nome.');return;}const result=await signUp(email.trim(),password,name.trim());if(result.access_token)await prepare(result);else{setMessage('Cadastro realizado. Confirme o e-mail recebido e depois entre na conta.');setRegister(false);}}else{await prepare(await signInWithPassword(email.trim(),password));localStorage.removeItem(LOGIN_GUARD_KEY);setLoginGuard({attempts:0,lockedUntil:0});}}catch(e){if(!register&&isInvalidCredentials(e)){const attempts=loginGuard.attempts+1;const next=attempts>=MAX_LOGIN_ATTEMPTS?{attempts:0,lockedUntil:Date.now()+LOCK_DURATION_MS}:{attempts,lockedUntil:0};localStorage.setItem(LOGIN_GUARD_KEY,JSON.stringify(next));setLoginGuard(next);setError(attempts>=MAX_LOGIN_ATTEMPTS?'Acesso bloqueado por 15 minutos após 5 tentativas incorretas.':`E-mail ou senha incorretos. Restam ${MAX_LOGIN_ATTEMPTS-attempts} tentativa(s).`);}else setError(friendly(e));}finally{setLoading(false);}};
 const submitNewPassword=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');if(newPassword.length<8){setError('A nova senha deve ter pelo menos 8 caracteres.');return;}if(newPassword!==confirmPassword){setError('As senhas não coincidem.');return;}setLoading(true);try{await updatePassword(newPassword);localStorage.removeItem(LOGIN_GUARD_KEY);setLoginGuard({attempts:0,lockedUntil:0});setRecoveryMode(false);history.replaceState(null,'',location.pathname);setMessage('Senha alterada com sucesso. Você já pode acessar a aplicação.');}catch(e){setError(friendly(e));}finally{setLoading(false);}};
 if(!ready)return <div className="min-h-screen grid place-items-center bg-slate-950 text-white"><Loader2 className="h-8 w-8 animate-spin"/></div>;
 if(recoveryMode)return <main className="min-h-screen bg-slate-950 text-slate-100 grid place-items-center p-4"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900 p-6 sm:p-8 shadow-2xl"><div className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-indigo-600"><LockKeyhole className="h-6 w-6"/></div><h1 className="text-center text-2xl font-black">Criar nova senha</h1><p className="mt-2 text-center text-sm text-slate-400">Digite uma senha nova para sua conta.</p>{error&&<div role="alert" className="mt-5 rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</div>}{message&&<div role="status" className="mt-5 rounded-xl border border-emerald-800 bg-emerald-950/40 p-3 text-sm text-emerald-200">{message}</div>}<form onSubmit={submitNewPassword} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Nova senha<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={8} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3" required/></label><label className="block text-sm font-semibold">Confirmar nova senha<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={8} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3" required/></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 font-bold disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<LockKeyhole className="h-4 w-4"/>}Salvar nova senha</button></form></div></main>;
 if(session||isPublicValidation())return <>{children}</>;
 return <main className="min-h-screen bg-slate-950 text-slate-100 grid place-items-center p-4"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900 p-6 sm:p-8 shadow-2xl"><div className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-indigo-600"><LockKeyhole className="h-6 w-6"/></div><h1 className="text-center text-2xl font-black">Certificados</h1><p className="mt-2 text-center text-sm text-slate-400">{recoveryRequest?'Informe seu e-mail para receber o link de redefinição.':register?'Crie a conta responsável pela instituição.':'Entre para acessar e sincronizar os certificados.'}</p>{error&&<div role="alert" className="mt-5 rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</div>}{message&&<div role="status" className="mt-5 rounded-xl border border-emerald-800 bg-emerald-950/40 p-3 text-sm text-emerald-200">{message}</div>}<form onSubmit={submit} className="mt-6 space-y-4">{register&&!recoveryRequest&&<label className="block text-sm font-semibold">Nome<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3" required/></label>}<label className="block text-sm font-semibold">E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3" required/></label>{!recoveryRequest&&<label className="block text-sm font-semibold">Senha<input type="password" autoComplete={register?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={6} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3" required/></label>}<button disabled={loading||(!register&&!recoveryRequest&&loginGuard.lockedUntil>Date.now())} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 font-bold disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Cloud className="h-4 w-4"/>}{recoveryRequest?'Enviar link':register?'Criar conta':loginGuard.lockedUntil>Date.now()?'Acesso temporariamente bloqueado':'Entrar e sincronizar'}</button></form><div className="mt-5 space-y-3"><button onClick={()=>{setRecoveryRequest(v=>!v);setRegister(false);setError('');setMessage('')}} className="w-full text-sm font-semibold text-indigo-300">{recoveryRequest?'Voltar para o login':'Esqueci minha senha'}</button>{!recoveryRequest&&<button onClick={()=>{setRegister(v=>!v);setError('');setMessage('')}} className="w-full text-sm font-semibold text-indigo-300">{register?'Já tenho uma conta':'Criar minha conta'}</button>}</div><p className="mt-6 text-center text-[11px] text-slate-500">Os dados são protegidos por autenticação e regras de acesso no Supabase.</p></div></main>;
};
