import { isValidCpf } from '../utils/validation';
import { writeTransaction } from '../utils/persistence';
import React,{createContext,useContext,useEffect,useRef,useState}from'react';
import{Course,Student,Certificate,InstitutionSettings}from'../types';
import{INITIAL_INSTITUTION,INITIAL_COURSES,INITIAL_STUDENTS,INITIAL_CERTIFICATES}from'../utils/storage';
import{generateCertificateCode}from'../utils/codeGenerator';import{generateUUID,calculateCertificateHash}from'../utils/integrity';
interface AppContextType{currentView:string;setCurrentView:(v:string)=>void;theme:'light'|'dark';toggleTheme:()=>void;institution:InstitutionSettings;updateInstitution:(s:Partial<InstitutionSettings>)=>void;courses:Course[];students:Student[];addStudent:(s:Omit<Student,'id'|'createdAt'>)=>Student;updateStudent:(id:string,u:Partial<Student>)=>void;deleteStudent:(id:string)=>void;certificates:Certificate[];issueCertificate:(c:Omit<Certificate,'id'|'uuid'|'code'|'integrityHash'|'status'|'createdAt'>)=>Certificate;cancelCertificate:(id:string,reason:string)=>void;getCertificateByCode:(code:string)=>Certificate|undefined;selectedCertificateId:string|null;setSelectedCertificateId:(id:string|null)=>void;validationSearchCode:string;setValidationSearchCode:(code:string)=>void;resetToDemoData:()=>void;clearAllData:()=>void;}
const AppContext=createContext<AppContextType|undefined>(undefined);const K={INSTITUTION:'certifyai_institution',COURSES:'certifyai_courses',STUDENTS:'certifyai_students',CERTIFICATES:'certifyai_certificates',THEME:'certifyai_theme',DATA_VERSION:'certifyai_data_version'};const DATA_VERSION='cvte-final-local-v1';const read=<T,>(k:string,f:T):T=>{try{const v=typeof window!=='undefined'?localStorage.getItem(k):null;return v?JSON.parse(v):f}catch{return f}};
function useStoredState<T>(key:string, fallback:T) {
 const [value,setValue]=useState<T>(()=>read(key,fallback));
 const ref=useRef(value);
 const update=(next:T|((current:T)=>T), persist=true)=>{const resolved=typeof next==='function'?(next as (v:T)=>T)(ref.current):next;if(persist)writeTransaction(localStorage,{[key]:JSON.stringify(resolved)});ref.current=resolved;setValue(resolved);};
 return [value,update,ref] as const;
}
export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{const [storageError,setStorageError]=useState(false);useEffect(()=>{const onError=()=>setStorageError(true);window.addEventListener('certifyai-storage-error',onError);return()=>window.removeEventListener('certifyai-storage-error',onError);},[]);const[theme,setTheme]=useStoredState<'light'|'dark'>(K.THEME,'light');const[currentView,setCurrentView]=useState('dashboard');const[selectedCertificateId,setSelectedCertificateId]=useState<string|null>(null);const[validationSearchCode,setValidationSearchCode]=useState('');const[institution,setInstitution]=useStoredState(K.INSTITUTION,INITIAL_INSTITUTION);const[courses,setCourses,coursesRef]=useStoredState<Course[]>(K.COURSES,INITIAL_COURSES);const[students,setStudents,studentsRef]=useStoredState<Student[]>(K.STUDENTS,INITIAL_STUDENTS);const[certificates,setCertificates,certificatesRef]=useStoredState<Certificate[]>(K.CERTIFICATES,INITIAL_CERTIFICATES);const codes=useRef(certificates.map(c=>c.code));
useEffect(()=>{codes.current=certificates.map(c=>c.code)},[certificates]);useEffect(()=>{if(typeof window==='undefined')return;const params=new URLSearchParams(location.search),m=location.pathname.match(/^\/verificar\/([^/]+)$/i),code=params.get('verify')||params.get('code')||(m?decodeURIComponent(m[1]):null);if(code){setValidationSearchCode(code);setCurrentView('validate')}},[]);useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark')},[theme]);
const toggleTheme=()=>setTheme(v=>v==='light'?'dark':'light');const updateInstitution=(s:Partial<InstitutionSettings>)=>setInstitution(v=>({...v,...s}));const addStudent=(d:Omit<Student,'id'|'createdAt'>)=>{const s={...d,id:`student-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:new Date().toISOString()};setStudents(v=>[s,...v]);return s};const updateStudent=(id:string,u:Partial<Student>)=>setStudents(v=>v.map(s=>s.id===id?{...s,...u}:s));const deleteStudent=(id:string)=>setStudents(v=>v.filter(s=>s.id!==id));
const issueCertificate=(d:Omit<Certificate,'id'|'uuid'|'code'|'integrityHash'|'status'|'createdAt'>)=>{if(!d.studentDocument || !isValidCpf(d.studentDocument))throw new Error('Informe um CPF válido.');const code=generateCertificateCode(certificatesRef.current.map(c=>c.code),institution.codeFormat||'cvte');const existing=studentsRef.current.find(s=>s.id===d.studentId)||studentsRef.current.find(s=>(s.documentNumber||'').replace(/\D/g,'')===(d.studentDocument||'').replace(/\D/g,''));const student=existing||{id:generateUUID(),fullName:d.studentName,email:d.studentEmail||'',documentNumber:d.studentDocument,registrationNumber:d.registrationNumber,cnhCategory:d.cnhCategory,courseId:d.courseId,createdAt:new Date().toISOString()};const partial={...d,studentId:student.id,id:`cert-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,uuid:generateUUID(),code,templateId:'official' as const,status:'active' as const,createdAt:new Date().toISOString()};const cert:Certificate={...partial,integrityHash:calculateCertificateHash(partial)};writeTransaction(localStorage,{[K.CERTIFICATES]:JSON.stringify([cert,...certificatesRef.current]),[K.STUDENTS]:JSON.stringify(existing?studentsRef.current:[student,...studentsRef.current])});if(!existing)setStudents(v=>[student,...v],false);setCertificates(v=>[cert,...v],false);return cert};const cancelCertificate=(id:string,reason:string)=>setCertificates(v=>v.map(c=>c.id===id?{...c,status:'cancelled' as const,cancelledAt:new Date().toISOString(),cancelledBy:'Instituição emissora',cancellationReason:reason}:c));const getCertificateByCode=(code:string)=>certificates.find(c=>c.code.toUpperCase()===code.trim().toUpperCase());
const resetToDemoData=()=>{setInstitution(INITIAL_INSTITUTION);setCourses(INITIAL_COURSES);setStudents([]);setCertificates([]);codes.current=[];localStorage.setItem(K.DATA_VERSION,DATA_VERSION)};const clearAllData=()=>{setCourses(INITIAL_COURSES);setStudents([]);setCertificates([]);codes.current=[];Object.values(K).forEach(k=>localStorage.removeItem(k))};return <AppContext.Provider value={{currentView,setCurrentView,theme,toggleTheme,institution,updateInstitution,courses,students,addStudent,updateStudent,deleteStudent,certificates,issueCertificate,cancelCertificate,getCertificateByCode,selectedCertificateId,setSelectedCertificateId,validationSearchCode,setValidationSearchCode,resetToDemoData,clearAllData}}>{storageError&&<div role="alert" className="sticky top-0 z-[200] bg-rose-100 text-rose-900 p-4">Não foi possível salvar a última alteração. Faça um backup e verifique o espaço do navegador.<button className="ml-4 underline" onClick={()=>setStorageError(false)}>Fechar aviso</button></div>}{children}</AppContext.Provider>};export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error('useApp must be used within AppProvider');return c};

